In [4]:
import tensorflow as tf
import pathlib
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

np.set_printoptions(precision=4)

In [12]:
dataset = tf.data.Dataset.range(8)
dataset = dataset.batch(3, drop_remainder=True)
for i in dataset:
  print(i)

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([3 4 5], shape=(3,), dtype=int64)


In [14]:
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])
for elem in dataset:
  print(elem.numpy())

8
3
0
8
2
1


In [17]:
it = iter(dataset)

print(next(it).numpy())
print(next(it).numpy())
print(next(it).numpy())
print(next(it).numpy())

8
3
0
8


In [18]:
print(dataset.reduce(0, lambda state, value: state + value).numpy())

22


In [20]:
dataset1 = tf.data.Dataset.from_tensor_slices(
    tf.random.uniform([4, 10], minval=1, maxval=10, dtype=tf.int32))

dataset1

<_TensorSliceDataset element_spec=TensorSpec(shape=(10,), dtype=tf.int32, name=None)>

In [21]:
for z in dataset1:
  print(z.numpy())

[4 4 5 5 9 8 3 8 9 6]
[9 7 3 5 2 6 7 9 3 9]
[3 7 6 1 5 1 5 3 8 1]
[8 5 4 2 5 7 7 6 1 1]


In [22]:
dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))

dataset2

<_TensorSliceDataset element_spec=(TensorSpec(shape=(), dtype=tf.float32, name=None), TensorSpec(shape=(100,), dtype=tf.int32, name=None))>

In [23]:
for z in dataset1:
  print(z.numpy())

[4 4 5 5 9 8 3 8 9 6]
[9 7 3 5 2 6 7 9 3 9]
[3 7 6 1 5 1 5 3 8 1]
[8 5 4 2 5 7 7 6 1 1]


## Reading input data

If all of your input data fits in memory, the simplest way to create a `Dataset` from them is to convert them to `tf.Tensor` objects and use `Dataset.from_tensor_slices`.

In [24]:
train, test = tf.keras.datasets.fashion_mnist.load_data()

4422102/4422102 [==============================] - 0s 0us/step


In [25]:
images, labels = train
images = images/255.

dataset = tf.data.Dataset.from_tensor_slices((images, labels))
dataset

<_TensorSliceDataset element_spec=(TensorSpec(shape=(28, 28), dtype=tf.float64, name=None), TensorSpec(shape=(), dtype=tf.uint8, name=None))>

In [26]:
# Creates a dataset that reads all of the examples from two files.
fsns_test_file = tf.keras.utils.get_file("fsns.tfrec", "https://storage.googleapis.com/download.tensorflow.org/data/fsns-20160927/testdata/fsns-00000-of-00001")

7904079/7904079 [==============================] - 0s 0us/step


In [27]:
dataset = tf.data.TFRecordDataset(filenames = [fsns_test_file])
dataset

<TFRecordDatasetV2 element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>